/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package pe.edu.uni.proyecto1_quispe.view;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import javax.swing.JInternalFrame;

/**
 *
 * @author PROFESOR
 */
public class TrianguloMDI extends javax.swing.JFrame {

    /**
     * Creates new form TrianguloMDI
     */
    public TrianguloMDI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuEscaleno = new javax.swing.JMenu();
        menuItemEscaleno = new javax.swing.JMenuItem();
        menuItemIsosceles = new javax.swing.JMenuItem();
        menuItemEquilatero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuEscaleno.setText("Triángulo");
        menuEscaleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEscalenoActionPerformed(evt);
            }
        });

        menuItemEscaleno.setText("Escaleno");
        menuItemEscaleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEscalenoActionPerformed(evt);
            }
        });
        menuEscaleno.add(menuItemEscaleno);

        menuItemIsosceles.setText("Isósceles");
        menuItemIsosceles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIsoscelesActionPerformed(evt);
            }
        });
        menuEscaleno.add(menuItemIsosceles);

        menuItemEquilatero.setText("Equilátero");
        menuItemEquilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEquilateroActionPerformed(evt);
            }
        });
        menuEscaleno.add(menuItemEquilatero);

        menuBar.add(menuEscaleno);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEscalenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEscalenoActionPerformed
        
    }//GEN-LAST:event_menuEscalenoActionPerformed

    private void menuItemEscalenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEscalenoActionPerformed
        JInternalFrame view = new TrianguloEscalenoView();
        desktopPane.add(view);
        view.setVisible(true);
    }//GEN-LAST:event_menuItemEscalenoActionPerformed

    private void menuItemIsoscelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIsoscelesActionPerformed
        JInternalFrame view = new TrianguloIsoscelesView();
        desktopPane.add(view);
        view.setVisible(true);
    }//GEN-LAST:event_menuItemIsoscelesActionPerformed

    private void menuItemEquilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEquilateroActionPerformed
        JInternalFrame view = new TrianguloEquilateroView();
        desktopPane.add(view);
        view.setVisible(true);
    }//GEN-LAST:event_menuItemEquilateroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrianguloMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrianguloMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrianguloMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrianguloMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrianguloMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEscaleno;
    private javax.swing.JMenuItem menuItemEquilatero;
    private javax.swing.JMenuItem menuItemEscaleno;
    private javax.swing.JMenuItem menuItemIsosceles;
    // End of variables declaration//GEN-END:variables

}
